// Builds src/fonts/jp.css: the Japanese faces the site uses, limited to the characters it uses.
//
// Each Japanese face ships as ~120 subset files (one per unicode-range). Bundling them all would put
// hundreds of files in the build for a site that shows a few dozen kanji and kana, so this copies
// only the subsets that contain a character found in the source, and declares them under
// "Luffy JP *" family names that the CSS font stacks fall back to.
//
// Run after changing any Japanese text:  node scripts/jp-fonts.mjs
import { readFileSync, writeFileSync, readdirSync, statSync, copyFileSync, mkdirSync, rmSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, "src", "fonts");
const FACES = [
  { family: "Luffy JP Display", pkg: "shippori-mincho-b1", weight: 700, range: "700 800" },
  { family: "Luffy JP Body", pkg: "zen-kaku-gothic-new", weight: 400, range: "400 500" },
  { family: "Luffy JP Body", pkg: "zen-kaku-gothic-new", weight: 700, range: "700" },
  { family: "Luffy JP Brush", pkg: "yuji-syuku", weight: 400, range: "400" },
];

// 1. Every CJK character in the site's source.
const isJp = (cp) => (cp >= 0x3000 && cp <= 0x30ff) || (cp >= 0x3400 && cp <= 0x9fff) || (cp >= 0xff00 && cp <= 0xffef);
const chars = new Set();
const walk = (dir) => {
  for (const f of readdirSync(dir)) {
    const p = join(dir, f);
    if (statSync(p).isDirectory()) { if (f !== "fonts") walk(p); continue; }
    if (!/\.(tsx?|html|css)$/.test(f)) continue;
    for (const ch of readFileSync(p, "utf8")) if (isJp(ch.codePointAt(0))) chars.add(ch.codePointAt(0));
  }
};
["src", "film"].forEach((d) => walk(join(root, d)));

// 2. Subsets that cover them.
const parseRange = (r) => r.split(",").map((s) => {
  const [a, b] = s.trim().replace(/^U\+/i, "").split("-");
  return [parseInt(a, 16), parseInt(b ?? a, 16)];
});
rmSync(out, { recursive: true, force: true });
mkdirSync(out, { recursive: true });
let css = `/* Generated by scripts/jp-fonts.mjs from ${chars.size} characters — do not edit. */\n`;
let files = 0;
for (const f of FACES) {
  const pkgDir = join(root, "node_modules", "@fontsource", f.pkg);
  const src = readFileSync(join(pkgDir, `${f.weight}.css`), "utf8");
  for (const block of src.split("@font-face").slice(1)) {
    const url = /url\(\.\/files\/([^)]+\.woff2)\)/.exec(block)?.[1];
    const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1];
    if (!url || !range || !/-\d+-\d+-normal\.woff2$/.test(url)) continue; // numbered CJK subsets only
    const ranges = parseRange(range);
    const hit = [...chars].some((cp) => ranges.some(([a, b]) => cp >= a && cp <= b));
    if (!hit) continue;
    copyFileSync(join(pkgDir, "files", url), join(out, url));
    files++;
    css += `@font-face{font-family:"${f.family}";font-style:normal;font-display:swap;font-weight:${f.range};src:url(./${url}) format("woff2");unicode-range:${range};}\n`;
  }
}
writeFileSync(join(out, "jp.css"), css);
console.log(`${chars.size} characters → ${files} font files in src/fonts`);
